RIOT-OS/rust-riot-wrappers

Cargo.toml, README.md, src/lib.rs
* It's now maintained inside RIOT
* Some crate docs were added (enough to get the pointers to more docs)
* Minor corrections
=> Updates to README and documentation

src/gcoap.rs
Building on https://github.com/RIOT-OS/rust-riot-sys/pull/5, this add support for the RIOT API change of https://github.com/RIOT-OS/RIOT/pull/17957 in a way that is transparent to coap-handler users. (The extra information now accessible is lost to Rust users, but any change there would likely be an API change on the coap-handler/coap-message side, exposing the new features, or a new API that gives lower-level control of request handling).
* Green CI
* https://github.com/RIOT-OS/RIOT/pull/17957 switches over to using this and *also* gets a green CI
=> Adjust to Gcoap handler taking a coap_request_ctx_t rather than a void*

src/helpers.rs, src/saul.rs, src/saul/registration.rs
This was not spotted in [18043] that caused the API break, because none
of the CI built examples have SAUL enabled.
[18043]: https://github.com/RIOT-OS/RIOT/pull/18043
=> saul: Tolerate switched callback pointer type

src/lib.rs, src/shell.rs
The static_command! macro previously required the using crate to also
use riot-sys. As the need to pick a suitable riot-sys has been annoying
in different places, this adds a public re-export of riot-sys, which can
then be used by macros and users.
=> Re-export riot-sys, use it in static_command!

Cargo.toml, src/gcoap.rs, src/saul.rs, src/vfs.rs, src/ztimer/periodic.rs
<del>Do not merge yet: This will need to bump the riot-sys depenedency to the one where the markers are actually frozen (0.7.8), but that's not out yet.</del>
This removes some obsolete ifdefs required only for RIOT versions earlier than the currently stable one, and that was there to accommodate API breaking PRs that were eventually not accepted.
=> Remove obsolete code after marker freezes

Cargo.toml
Changes:
* Adjust to RIOT API changes after 2022.04 in SAUL and Gcoap
* Publicly export the used version of riot-sys
* Remove ifdefs for API variations before 2022.04
* Documentation fixes
* Migrate into the RIOT project, to
https://github.com/RIOT-OS/rust-riot-wrappers
* Adjust CI to RIOT's hoster
=> Release 0.7.23

.github/workflows/buildtest.yml
Currently, failures just look like this:
```
Building for native ... success.
Building for sltb001a ... failed!
Building for samr21-xpro ... failed!
```
This enables debug output, as it already was back on GitLab.
=> CI: Make buildtest more verbose

Cargo.toml
This was temporarily switched to a pre-release version in https://github.com/RIOT-OS/rust-riot-wrappers/pull/10 but now is generally available.
=> dependencies: Use released cstr

Cargo.toml
Changes:
* All deprecated modules and features removed.
Noteworthy are the ones that did not perviously raise deprecation warnings automatically:
* Features that were previously default are now not default any more. A crate that is a main application should now use the `set_panic_handler` feature.
* rnrc::Pktsnip does not implement From<*mut gnrc_pktsnip_t> any more
* i2c::Error and thread::StackStats are now non_exhaustive
* Several error types changed from Option<T> or Result<T, ()> to meaningful ZST errors. These are located in the thread, GNRC and gcoap modules, and are best found by the compiler.
* stdio::read_raw now returns the raw error code error::NumericError.
* The crate's CStr switched from the cstr_core crate to the recently stabilized core::CStr. There is still a crate …
=> Bump version to 0.8.0

src/mutex.rs
This is a precondition of the C code, and might be UB otherwise.
---
Explicitly checking might bring a performance impact, and removes us from being a zero-cost abstraction, but safety is a preeminent requirement for Rust wrappers.
=> mutex: Panic when called from interrupt context

src/main_module.rs
This deprecates riot_main_with_tokens, which is now merely a compatibility alias for riot_main.
Closes: https://github.com/RIOT-OS/rust-riot-wrappers/issues/27
See the referenced issue for motivation; also, this removes clutter from the invocation.
=> riot_main: Implement for all relevant signatures

src/main_module.rs, src/thread.rs, src/thread/tokenparts.rs
Both renames are compatible in that the old names become deprecated aliases.
Closes: https://github.com/RIOT-OS/rust-riot-wrappers/issues/28
=> Rename TerminationToken to EndToken, and .termination() to .can_end()

Cargo.toml, src/led.rs
Closes: https://gitlab.com/etonomy/riot-wrappers/-/issues/5
The GPIO implementation is left in place, both for compatibility and for convenience.
=> LEDs: Add switch-hal

Cargo.toml, src/interrupt.rs, src/lib.rs, src/mutex.rs, src/panic.rs, src/thread.rs, src/thread/tokenparts.rs
Tokens for being-in-a-thread have only been a comment previously, and came to prominence through https://github.com/RIOT-OS/rust-riot-wrappers/issues/18 and [a reddit thread](https://www.reddit.com/r/linux/comments/xt9uq2/comment/iqqa0pv/).
As a first demo, the tokens can be used with a Mutex when locking. This does not close #18, as the mutex function stays as it is -- but it might be deprecated, or (compatibly ... how?) changed to return a Result that the user would then need to unwrap (but does that make it better? Might it just be deprecated?).
As they work just the same, it also adds tokens for "being in an interrupt context", although there's probably not much that can be done with them (because interrupts could still be nested).
More APIs should probably switch from being …
=> Add tokens for being in a thread

Cargo.toml
Changes:
* TokenParts: Add InThread and InIsr, deprecating `irq_is_in` & co.
* Add ValueInThread based on InThread, allowing safer use of a Mutex
* Shell: Provide more practical `run_providing_buf` method, deprecating the methods that take a buffer.
* Unify `riot_main` and `riot_main_with_tokens`, deprecating the latter.
* LEDs: Implement switch-hal
* Rename `TerminationToken` to `EndToken` (and `.termination()` to `.can_end()`)
* Mutex: Panic instead of trying to lock in an ISR
* Add tests
---
Except for this change that changes the version number, this is exactly what RIOT uses since https://github.com/RIOT-OS/RIOT/pull/19193.
=> Bump version to 0.8.1

.github/workflows/buildtest.yml, src/mutex.rs, src/thread/tokenparts.rs, tests/README.md, tests/led/tests/01-run.py, tests/mutex/Cargo.toml, tests/mutex/Makefile, tests/mutex/src/lib.rs, tests/mutex/tests/01-run.py
This primarily fixes #41, and adds infrastructure to also run (not only build) tests, as well as a test that'd have caught this.
=> Fix and tests mutex wrapper

src/gcoap.rs
While most Gcoap listeners are set up around some main loop in practice (which allows using items whose lifetime is not static but just exceeds that main loop), there are corner cases where that is not practical -- for example in auto init situations.
This is sound and can thus be used without unsafe because all data that goes into the registration has static lifetime, and the Gcoap server doesn't run longer than that either.
=> gcoap: Allow registration without scope for 'static listeners

src/coap_handler.rs, src/gcoap.rs
gcoap takes a link encoder to allow listeners customization of what they write into .well-known/core. So far, this has not been exercised by the RIOT wrappers, resulting in the use of the default handler (which just emits the path). This fell short when the resource had metadata, or when multiple resources were dispatched through Rust mechanisms under any given path.
This adds two things:
* A way for a rust-wrapped SingleHandlerListener to encode its own links
* An update to the coap_handler Gcoap wrapper that utilizes the coap_handler::Reporting information to produce sensible information.
This is all falling a bit short due to the lack of block-wise transfer in Gcoap's .well-known/core, but hey, it's a start.
=> gcoap: Provide link encoder

build.rs, src/auto_init.rs, tests/auto-init-debug/Cargo.toml, tests/auto-init-debug/Makefile, tests/auto-init-debug/src, tests/auto-init-debug/tests/01-run.py
A signed-vs-unsigned char bug hid in code that's dead without debug that only manifests on ARM.
=> tests: Add test for auto-init when auto-init debug is active

src/saul.rs
https://github.com/RIOT-OS/RIOT/pull/19292 has cleaned up in the G* unit names. #46 was created to make that change work with Rust, before it was found that using variant aliases on the C side makes that a non-issue.
What remains is using the "good" names on the Rust side. AFAICT the way it's done in this PR (renaming the variant and introducing a const in the impl, as suggested [on stackoverflow](https://stackoverflow.com/a/50472444)) is semver compatible. This PR picks up ideas from @maribu's #46, but touches different parts.
This doesn't change the names on the C side yet -- there are aliases in place we can use, and while using a marker is not as complicated any more as it used to be, not doing anything until the last release works too, so why do extra work.
=> saul: Compatibly rename G* variants

.github/workflows/buildtest.yml, src/dac.rs, src/lib.rs, tests/dac/Cargo.toml, tests/dac/Makefile, tests/dac/src/lib.rs
Adds a wrapper around RIOTS [dac-interface](https://doc.riot-os.org/group__drivers__periph__dac.html)
=> DAC: Add wrapper around RIOTs DAC-interface

src/saul.rs
The compatible renaming of https://github.com/RIOT-OS/rust-riot-wrappers/pull/50 was actually not compatible for lack of a `pub` qualifier.
=> saul: Make G* renamings publicly available

src/error.rs
* error: Provide constants for common errors
* error: Use newer idioms, silence over-zealous deprecation warnings
* error: Deprecate direct access to .number, use .number() instead
While this is API cosmetics on the surface, it will allow changing the type's internals later on, eg. to make the negativity of its value an unsafe invariant (maybe even allowing the compiler to see the niches).
* error: Make from_constant const
* error: Derive PartialEq for NumericError
This started out as deriving PartialEq, and wound up enhancing usability on the whole.
=> Error enhancements

src/gnrc/ipv6.rs
Just a small housekeeping refactoring.
=> gnrc: Refactor Address to use an existing safe wrapper

src/lib.rs
This is migrating over a PR that was previously discussed at https://gitlab.com/etonomy/riot-wrappers/-/merge_requests/2
Current status is that [core::ffi::CStr::from_bytes_with_nul](https://doc.rust-lang.org/core/ffi/struct.CStr.html#method.from_bytes_with_nul) becomes stably const. This is tracked at https://github.com/rust-lang/rust/issues/101719, which I understand to make best progress by letting it sit undisturbed long enough for a FCP to be started.
(The branch itself it a tad old, it might be easier to just have a do-over once that FCP is through).
=> Introduce BOARD const, deprecating board() function

src/auto_init.rs, src/bluetil.rs, src/gcoap.rs, src/gnrc.rs, src/gnrc/netreg.rs, src/gnrc/pktbuf.rs, src/gnrc_pktbuf.rs, src/interrupt.rs, src/lib.rs, src/main_module.rs, src/msg.rs, src/never.rs, src/panic.rs, src/saul.rs, src/saul/registration.rs, src/shell.rs, src/socket_embedded_nal_tcp.rs, src/thread.rs, src/thread/riot_c.rs, src/thread/stack_stats.rs, src/thread/tokenparts.rs, src/vfs.rs, tests/gnrc-pktbuf/Cargo.toml, tests/gnrc-pktbuf/Makefile, tests/gnrc-pktbuf/src/lib.rs, tests/gnrc-pktbuf/tests/01-run.py, tests/led/src/lib.rs, tests/mutex/src/lib.rs
Most of this is refactoring around discouraged patterns, but the warnings found an actual error when what was meant to be leaking a refcounted pktsnip (because the C function is taking ownership of it) only leaked the (Copy, hence the complaint from the linter) pointer, leading to use-after-free / double-free. (A tests was added to catch this).
<del>Set as a draft PR while I'm hunting the remaining warnings.</del>
=> Fix several compiler warnings

src/gnrc/ipv6.rs
When building with_embedded_nal, a build regression was introduced in 0ecf87e765f7264e79226540b694eb50993c7882 through careless refactoring. This restores buildability.
There is currently no test that'd have triggered this; adding tests is somewhere on the agenda, but fixing it is more urgent.
=> gnrc: Fix address conversion build failure

Cargo.toml, build.rs
As #48 has shown, picking flags out of the bindgen output is relatively brittle. It worked well for as long as we were only checking for some string's presence, but for CONFIG_ things we need a bit more.
This just uses the `syn` parser to parse the source code; that's a well established tool that's also used in proc macros.
Leaving this as a draft for a while to gather input and think more about it, but so far I like it.
=> build: Use `syn` to pick out constants

tests/random/Cargo.toml, tests/random/src/lib.rs
* If any of the tests fail, panic_format ensures the output can be understood easily.
* Some code was sent upstream to [1], a note ensures the local code can be removed when ready.
* Reducing the count of printed numbers to ensure that the default USB output buffer displays all relevant information and not just literally random stuff.
[1]: https://github.com/ryankurte/rngcheck/pull/3
=> random/tests: Small improvements

.github/workflows/test.yml
The tests are now run using individual steps for the same reasons the examples were switched over.
In [68], the tests were accidentally switched over to running all RIOT instead of all own tests (which may also make sense but is really excessive, and most importantly lost the own tests)
[68]: https://github.com/RIOT-OS/rust-riot-wrappers/pull/68
=> CI: Run own tests instead of RIOT tests

Cargo.toml, tests/.cargo/config.toml, tests/adc/Cargo.toml, tests/auto-init/Cargo.toml, tests/dac/Cargo.toml, tests/gnrc-pktbuf/Cargo.toml, tests/gpio/Cargo.toml, tests/i2c/Cargo.toml, tests/led/Cargo.toml, tests/mutex/Cargo.toml, tests/random/Cargo.toml, tests/ztimer-async/Cargo.toml
Marking the version currently being pulled into RIOT in https://github.com/RIOT-OS/RIOT/pull/20303
* Add autoinit module.
* Drop SUIT support. The module was in such disrepair in the previous that it was apparently not used.
* SAUL: Compatibly follow renaming of G* units done in C
* Add constants for common error values.
* Add initializers based on peripheral numbers.
* Add BOARD const.
* gcoap:
* Allow registration without scope for 'static listeners
* Provide link encoder based on coap_handler::wkc
* Support coap-message 0.3 / coap-handler 0.2
* Support embedded-hal 1.0 on selected modules.
* Add tests for mutex and random.
* Small refactorings.
* Fixes to existing tests.
* riot-sys is pulled to the latest version in this commit because there is no cross-version testing happening.
=> Bump version to 0.8.2

Cargo.toml, src/socket_embedded_nal_async_udp.rs
This is done in a compatible fashion. As there are no types that differ between the versions, all can be in private modules, and the code duplication is handled by a macro call.
=> Update embedded-nal to 0.7

Cargo.toml, README.md, build.rs, src/gcoap.rs
The main change in this PR is that instead of relying on riot-sys to export various pre-processed data, we just find riotbuild.h (which conveniently is an exported environment variable) and dig right into that.
This will allow riot-sys to no longer `links="riot-sys"`, and untangles the build steps. It may also speed things up, because now riot-wrappers will rebuild precisely when riotbuild.h changes.
On the downside, this has no provisions for further code dependent markers, which have in the past helped us across C API changes. A possible step forward on that is to just look at the relevant file in RIOTBASE to determine whether it contains a marker string -- also a way more direct method.
=> Simplify build.rs

src/gcoap.rs
The types u32/i32 were baked in there in carelessly following the type aliases.
Contributes-To: https://github.com/RIOT-OS/RIOT/pull/20339
=> gcoap: Fix incorrect function pointer signature

.github/workflows/test.yml, rustfmt.toml, src/coap_handler/v0_2.rs, src/coap_message/impl_0_2.rs, src/coap_message/impl_0_3.rs, src/gcoap.rs, src/gnrc_pktbuf.rs, src/gnrc_util.rs, src/microbit.rs, src/saul.rs, src/shell.rs, src/socket_embedded_nal.rs, src/spi/mod.rs, src/vfs.rs, src/ztimer/mod.rs
Going with the standard config (all customizations that were used required nightly) allows us to do the fmt checks on stable, which sidesteps problems around not every nightly having fmt.
The alternative was pinning to a nightly version, and that quickly gets old. (Hah.)
=> Drop nightly options for rustfmt

.github/workflows/test.yml, rustfmt.toml, src/coap_handler/v0_2.rs, src/coap_message/impl_0_2.rs, src/coap_message/impl_0_3.rs, src/gcoap.rs, src/gnrc_pktbuf.rs, src/gnrc_util.rs, src/microbit.rs, src/panic.rs, src/saul.rs, src/shell.rs, src/socket_embedded_nal.rs, src/spi/mod.rs, src/thread/riot_c.rs, src/vfs.rs, src/ztimer/mod.rs
One or more small tunings toward enhanced binary size
* `Thread::get_name()`: On a DEVELHELP=0 minimal example, this saves 700 byte binary. (rust_begin_unwind would otherwise construct a Rust str out of a cstr, when normally it can know all arguments to write_str).
* panic: Check for panic_handler_crash earlier. Saves another 100 bytes.
=> Microoptimizations

.github/workflows/test.yml
The property was set to see more characteristics of errors in a single CI run, but has led to CI checks showing green on the required all-done check when some tests failed.
In particular, https://github.com/RIOT-OS/rust-riot-wrappers/pull/84 would have become mergeable even though the rust-gcoap examples failed (for yet unknown reasons)
=> CI: Don't continue on error

.github/workflows/test.yml, Cargo.toml
Changes:
* Optimize panic handlers
panic_handler_crash now sidesteps additional error reporting that may have been possible depending on the interrupt state.
* Add support for embedded-nal-async 0.7
* Gcoap: Fix building on 64bit platforms
* Inspect BINDGEN_OUTPUT_FILE instead of linked riot-sys environment variables at build time
* Don't use custom rustfmt configuration
Waiting for https://github.com/RIOT-OS/RIOT/pull/20489 where those receive the extra testing of the full RIOT CI
=> Release 0.8.3

src/saul.rs
This makes functions that previously returned Option<&'static str> return None unconditionally due to the changes in https://github.com/RIOT-OS/RIOT/pull/20529.
Closes https://github.com/RIOT-OS/rust-riot-wrappers/issues/86, whose proposed change I took as a starting point.
@Teufelchen1, @maribu, does that look good to you?
(If so, next steps are we merge this here, I do an external-version-bump in RIOT, and then 20529 will succede)
=> Follow phydat access deprecations

src/ws281x.rs
Unblocks: https://github.com/RIOT-OS/RIOT/pull/20562
The module probably got broken when the inline functions were not automatically exported to the main namespace any more. Now that 20562 enables it on default boards, it is built the first time since 2021, and can now be built again.
There is no standalone test for this yet; it can be tested from RIOT by bending .cargo/config.toml to this branch, and running `USEMODULE+=ws281x make -C examples/rust-gcoap BOARD=microbit-v2` (which failed to build before, and now builds).
=> ws281x: Use static inline function through inline namespace

src/thread/riot_c.rs
Building on @maribu's #96, but can be merged without a flag-day change with RIOT
=>  thread: adapt to API change of thread_measure_stack_free() and accept either version

src/thread/riot_c.rs
This changes the API as needed for https://github.com/RIOT-OS/RIOT/pull/18942
=> thread: adapt to API change of thread_measure_stack_free()

src/saul.rs
This is a breaking change, and should be held until short before the next "major" version change.
It will allow adding new variants, and should have been done from the start.
=> saul: Make Unit non_exhaustive

Cargo.toml
Hey 🦋
This change is needed to compile RIOT/examples/rust-hello-world for the GBA.
I am aware that this is not the right way to do it but I am not yet proficient with Rust yet, so... please help! :) 
The `portable-atomic` [documentation](https://docs.rs/portable-atomic/latest/portable_atomic/) even mentions the GBA.
The version bump of `heapless` is needed as [the feature](https://docs.rs/crate/heapless/latest/features#portable-atomic-unsafe-assume-single-core) is not yet present in `0.7.x`.
=> build: Select heapless-crate with features for GBA support

src/shell/mod.rs, tests/shell/Cargo.toml, tests/shell/Makefile, tests/shell/src/lib.rs, tests/shell/tests/01-run.py
This primarily fixes https://github.com/RIOT-OS/rust-riot-wrappers/issues/76 by returning an impl trait in a trait (which was not available back around 0.7 when that issue was introduced).
To avoid this kind of regressions in the future, a test is added.
=> Shell: Usability fixes and test

src/ztimer/mod.rs, tests/ztimer-async/src/lib.rs, tests/ztimer/Cargo.toml, tests/ztimer/Makefile, tests/ztimer/src/lib.rs, tests/ztimer/tests/01-run.py
This adds a way to acquire a clock, a `.now()` method on acquired clock, and `.time()` method for timing functions as they are being executed.
=> Use ztimer_acquire and provide methods based on that kind of locking

Cargo.toml, build.rs, src/coap_message/impl_0_3.rs, src/gcoap.rs, src/gpio/mod.rs, src/interrupt.rs, src/main_module.rs, src/saul/mod.rs, src/saul/registration.rs, src/socket_embedded_nal_async_udp.rs, src/ztimer/mod.rs
We've been racking up warnings, in part because changes to Rust caused so many warnings to show up that the relevant ones got drowned.
Fixing them piece by piece.
=> Various warning fixes

.github/workflows/test.yml, src/helpers.rs, src/impl_critical_section.rs, src/lib.rs, src/socket.rs, src/ztimer/mod.rs, tests/led/src/lib.rs, tests/random/src/lib.rs, tests/ztimer-async/src/lib.rs
This adds the equivalent of `-Werror` to the CI builds.
> While this is generally discouraged (for it means that new Rust versions break CI), in this case we don't get new Rust versions all the time but only on riotdocker updates, and that's a good time to reflect on whether the new warnings make sense or not.
Let's see how well that works; I rather add `#[allow(...)]` generously in the codebase than have so many warnings that important ones get overshadowed.
Along with the actual change, all the fixes that would previously have caused warnings (now errors) come in.
=> CI: Block warnings (with warnings fixes)

src/error.rs, src/vfs.rs
This fixes a severe bug where file names were passed to the C API that expects nul-termination.
This incurs some copying overhead, which fortunately is not too bad due to the name length limit.
Closes: https://github.com/RIOT-OS/rust-riot-wrappers/issues/93
Thanks @maikerlab for reporting this. AIU it went unnoticed because in my tests, the &str often came from what was originally nul-terminated, eg. from the command line, or from CoAP where the option byte is sometimes replaced with a \0 as a part gcoap's internal processing.
=> vfs: Buffer names for nul termination

src/vfs.rs
This is a breaking change; applications that used the old API were prone to broken file system linked lists and thus UB with some file systems (whose data in the directory struct was not the moral equivalent of Unpin).
Closes: https://gitlab.com/etonomy/riot-wrappers/-/issues/8
Note that I don't manage to crash the system with the original issue's description any more -- most likely, Rust/LLVM nowadays does more optimizations that avoid moving things, and thus avoids the bug by happenstance.
=> vfs: Change dir API to place directory in a pin rather than returning it bv value

src/ztimer/mod.rs, tests/ztimer/src/lib.rs
* sleep_ticks() becomes sleep()
* sleep() becomes sleep_extended()
Closes: https://github.com/RIOT-OS/rust-riot-wrappers/issues/66
=> ztimer: Rename functions

Cargo.toml, NEWS.md, src/vfs.rs, src/ztimer/mod.rs, tests/ztimer/src/lib.rs
This turns the version up to 0.9 for real (after a period on 0.8.999 since https://github.com/RIOT-OS/rust-riot-wrappers/pull/90).
Changing the version and pulling breaking changes from https://github.com/RIOT-OS/rust-riot-wrappers/pull/104 and https://github.com/RIOT-OS/rust-riot-wrappers/pull/108 means that this PR's CI will *not* pass. However, the individual PRs pulled in passed in their own PRs with "DO NOT MERGE" commits on top that bend the affected repositories (RIOT, riot-module-examples) to the respective 0.9 branch.
This PR will be merged ignoring the failing CI. Once it is published, RIOT and riot-module-examples can get their own updates that go to 0.9. The alternative to this rather brutal approach is to bend CI now to test against the branches, and then do an extra PR …
=> Change version to 0.9, merging breaking changes

src/gpio/mod.rs, src/main_module.rs, src/msg/v2.rs
With work going on on https://github.com/RIOT-OS/rust-documentation-builder for more reliable documentation and tests building, a few bugs (and overly complicated constructs) were found in this crate's doctests, and fixed here.
This is also the first PR since the 0.9 manual merging and subsequent update of RIOT, so let's see how CI fares.
=> doc: Make all doctests buildable once more

.github/workflows/test.yml, Cargo.toml, src/led.rs, tests/led/src/lib.rs
This adds a fallible constructor based on LEDn_IS_PRESENT.
Depends on https://github.com/RIOT-OS/rust-riot-sys/pull/45 -- this is a draft PR until that is released and this crate can bump its dependency version.
=> LEDs: Expose presence

Cargo.toml, src/led.rs, src/lib.rs, src/msg/mod.rs, src/msg/v2.rs, src/thread/tokenparts.rs
Several assert statements in the code were eligible for const promotion (turning them into build time errors) with 1.79, which is becoming available in CI as per https://github.com/RIOT-OS/RIOT/pull/20840
=> Use inline const of Rust 1.79

Cargo.toml, src/gcoap.rs, src/gnrc/ipv6.rs, src/gnrc/mod.rs, src/gnrc_pktbuf.rs, src/panic.rs, src/saul/registration.rs, src/ztimer/periodic.rs
Follow-up to https://github.com/RIOT-OS/rust-riot-wrappers/pull/115
=> More Rust 1.79 enhancements

.github/workflows/test.yml, build.rs, src/gnrc/mod.rs, src/gnrc/nib.rs, src/gnrc_util.rs, tests/network-properties/Cargo.toml, tests/network-properties/Makefile, tests/network-properties/src/lib.rs, tests/network-properties/tests/01-run.py
As suggested by @mcr.
<del>This is incomplete: It does not yet expose the various aspects of an entry's state.</del>
In practice, this could be used by a new riot-coap-handler-demos variant for output like this:
```
$ aiocoap-client coap://'[fe80::3c63:beff:fe85:ca96%tapbr0]'/nib/neigh
[_
[
6,
h'862e80417409',
IP'fe8::f30:40e4:6c93:e17d',
"reachable",
"GC",
],
]
```
=> nib: New module to add neighbor cache access

src/led.rs
As this is expected to be used by newcomers, it helps being explicit.
=> doc: Explicitly spell out constructor

src/adc.rs, src/async_helpers.rs, src/gpio/mod.rs
The fixes in [125] made the warnigns go away, but [`.foo()`] does not fix the warnings, it just looks so wrong that rustdoc doesn't even warn any more.
[125]: https://github.com/RIOT-OS/rust-riot-wrappers/pull/125
=> doc: Fix errors

src/adc.rs, src/async_helpers.rs, src/gpio/mod.rs
Thanks @Kijewski for suggesting this in https://github.com/RIOT-OS/rust-riot-wrappers/pull/126#discussion_r1761447593
=> doc: Fix errors more prettily

build.rs, src/gcoap.rs, src/gnrc/netreg.rs, src/msg/v2.rs
While [PR20900] provides a compatibility .hdr accessor through a union, that trick is not available through bindgen or c2rust, which all introduce a dummy-named field for the anonymous union. Instead, we follow the path set out by [PR79] and introspect the source file.
[PR20900]: https://github.com/RIOT-OS/RIOT/pull/20900
[PR79]: https://github.com/RIOT-OS/rust-riot-wrappers/pull/79
Replaces and thus closes: #129
@maribu, please verify that this aligns with [PR20900].
=> gcoap: adapt to API change in [PR20900]

src/gpio/mod.rs
C callers of gpio_read() do not care whether gpio_read() returns an pre C99 style `bool` (which is an `int` with every non-zero number being a valid representation of `true`) or C99 style `bool`, as long as the stay within spec (treating representation of `true` as `true` with no regard to the encoding).
This refactors the rust use to match the C behavior. This would allow updating `gpio_read()` to return C99 style `bool` as type.
=> gpio: Refactor use of RIOT's gpio_read()

src/shell/mod.rs
See https://github.com/RIOT-OS/RIOT/pull/20958
=> shell: change XFA format for !20958

Cargo.toml, README.md
Documentation is now synced into there, and the old URI is merely a redirect.
=> doc: Update URI

deny.toml
The latest version of `unicode-ident` switched license, which tripped up `cargo-deny` checks. See https://github.com/RIOT-OS/rust-riot-wrappers/pull/124#issuecomment-2508169864 for the long-term story, but to fix this now, the license is well within what can be allowed.
=> deny: Allow newer Unicode license

src/msg/v2.rs
A typo that the latest dictionary update caught.
This is cherry-picked from https://github.com/RIOT-OS/rust-riot-wrappers/pull/141 where it tripped up the CI checks, which should rebase onto this branch to avoid having that spurious commit in the PR.
=> msg: Typo fix

src/spi/for_embedded_hal_1.rs, src/spi/mod.rs, tests/spi/Cargo.toml, tests/spi/Makefile, tests/spi/src/lib.rs
SPI was the only peripheral that was stuck on embedded-hal 0.2 because there were major changes in the HAL, and because I had no test application.
So far, this is lacking:
* addressing the FIXME regarding the bus-as-a-whole devices
* tests (in particular on the non-in-place transfer, because that is complex and not used by my application test code)
=> spi: Add new embedded-hal 1.0 interface

src/error.rs, src/lib.rs, src/uart.rs, tests/uart/Cargo.toml, tests/uart/Makefile, tests/uart/src/lib.rs
This PR just contains fixes relative to https://github.com/RIOT-OS/rust-riot-wrappers/pull/39; let's keep discussion there, but it's a PR so that we can see what CI says.
=> UART wrapper (chrysn's cleanup)

.github/workflows/test.yml, build.rs, src/spi/for_embedded_hal_1.rs
When testing them with full RIOT, https://github.com/RIOT-OS/rust-riot-wrappers/pull/141 had errors like this:
```
100 |             clk: riot_sys::spi_clk_t_SPI_CLK_5MHZ,
|                            ^^^^^^^^^^^^^^^^^^^^^^ not found in `riot_sys`
```
This PR uses the cfg(accessible()) emulation to switch around between how the value is best accessed.
=> spi: Tolerate platforms defining their enums differently

Cargo.toml
RIOT is in hard freeze and this version is planned for 2025.01 -- and should thus also be on crates.io for easy use in out-of-tree applications.
There's a rustfmt underformatting that my local tools report; let's see what CI says, and look into whether anything needs to be added (but ideally after the release).
Procedurally, once this is ready to be merged, I'll upload the tag and then merge it. (I'm not familiar enough with the automation around that to trust GitHub actions to upload to crates.io).
---
Changes:
* UART support added.
* SPI reimplemented for embedded-hal 1.0.
* Adjust to RIOT API changes in gcoap, GPIO, shell XFA.
* Error enhancements (niche used, Display and Error added, pretty if tiny_strerror is available).
* GNRC enhancements (simplifications, debug, added methods).
* …
=> Bump version to 0.9.2

.github/workflows/test.yml, README.md
As follow-up of https://github.com/RIOT-OS/RIOT/pull/21135 and https://github.com/RIOT-OS/RIOT/pull/21221
(Note that the workflow is expected to fail until the latter PR is merged)
=> treewide: update links to RIOT examples

src/error.rs
As stated in the function's comment, `number` should be negated. Otherwise, things like `again_is_wouldblock` don't work correctly.
I think this missing was just an oversight from https://github.com/RIOT-OS/rust-riot-wrappers/commit/021cfa9cd8720e8e9049fb317592df9e3c46c8f0.
=> errors: Negate in `NumericError::from_constant`

src/shell/mod.rs
This needs to wait until we drop support for RIOT OS 2024.10, which will happen after the 2024.01 release.
See-Also: https://github.com/RIOT-OS/RIOT/pull/20958
See-Also: https://github.com/RIOT-OS/rust-riot-wrappers/pull/134
=> shell: Drop old XFA mechanism
